### ISSUE TITLE
Force Constant Calculation

### ISSUE THREAD

**Issue by nberkel05** [ericchansen/q2mm#14]
I tried doing a normal bond and angle force constants calculation. I got an error back pretty quickly. It seems to work for the ferrocene_ecl structure but not the ferrocene_stag. I've checked their files (01.in and .out) and can't tell the difference. Here's the error message:

```
Traceback (most recent call last):
  File "loop.py", line 183, in <module>
    main(sys.argv[1:])
  File "loop.py", line 177, in main
    loop.run_loop_input(lines)
  File "loop.py", line 114, in run_loop_input
    self.ref_data = calculate.main(self.args_ref)
  File "/afs/crc.nd.edu/user/n/nberkel/q2mm/calculate.py", line 104, in main
    data = collect_data(commands, inps, direc=opts.directory)
  File "/afs/crc.nd.edu/user/n/nberkel/q2mm/calculate.py", line 580, in collect_data
    hess.mass_weight_eigenvectors()
  File "/afs/crc.nd.edu/user/n/nberkel/q2mm/datatypes.py", line 723, in mass_weight_eigenvectors
    x, y = self.evecs.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```
I've attached relevant files.
[FC Error.zip](https://github.com/ericchansen/q2mm/files/172833/FC.Error.zip)

**Comment by nberkel05** [comment]
Turns out it was an issue with the last frequency in the .in file. There was no space between the two frequencies. By running another jaguar calculation and using those files instead, it seems to work now.
