### ISSUE TITLE
Exit status 3 from MacroModel

### ISSUE THREAD

**Issue by ericchansen** [ericchansen/q2mm#16]
I'm getting a new error, twice now in the past several days, that I'm not accustomed to.

simplex   -- Calculating MM3[FORWARD ParamMM3[af][1890,2](0.250303218289)](None).
FATAL -139: Could not check out a license for mmlibs version 2.5.
Traceback (most recent call last):
  File "loop.py", line 183, in <module>
    main(sys.argv[1:])
  File "loop.py", line 177, in main
    loop.run_loop_input(lines)
  File "loop.py", line 106, in run_loop_input
    self.ff = loop.opt_loop()
  File "loop.py", line 40, in opt_loop
    self.loop_lines, score=self.ff.score)
  File "loop.py", line 142, in run_loop_input
    self.ff = simp.run(r_data=self.ref_data)
  File "/scratch365/ehansen3/r_rhod/opt.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/scratch365/ehansen3/r_rhod/simplex.py", line 109, in run
    data = calculate.main(self.args_ff)
  File "/scratch365/ehansen3/r_rhod/calculate.py", line 102, in main
    some_class.run(check_tokens=opts.check)
  File "/scratch365/ehansen3/r_rhod/filetypes.py", line 1142, in run
    os.path.splitext(self.name_com)[0]), shell=True)
  File "/opt/crc/schrodinger/2014u1/mmshare-v25013/lib/Linux-x86_64/lib/python2.7/subprocess.py", lin\
e 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'bmin -WAIT X004.q2mm' returned non-zero exit status 3

I checked X004.q2mm.log, and it appears normal. However, this is probably a log file from a previous calculation, not the one that caused this error. Nonetheless, the log is attached.

I checked the number of licenses available manually ~ 1 hour after being notified of this error. 8/25 tokens were checked out. It would seem strange that ~ 1 hour ago, all 24 tokens were consumed such that this job would fail.

Anyone have ideas?

Also attached is the log file for the job.

Renamed all attached files as text files.

[rhod_b094.o996333.txt](https://github.com/ericchansen/q2mm/files/231109/rhod_b094.o996333.txt)

[X004.q2mm.log.txt](https://github.com/ericchansen/q2mm/files/231110/X004.q2mm.log.txt)

**Comment by arosale4** [comment]
From looking at the Job Control Guide for Schrodinger. Error 139 refers to a segmentation fault, so its possibly a memory issue?

**Comment by ericchansen** [comment]
It's a simple energy comparison loop, so I doubt it's memory. Attached is the input for loop. I have a hard time seeing that consume the available memory.

[b094.com.txt](https://github.com/ericchansen/q2mm/files/232041/b094.com.txt)

**Comment by ericchansen** [comment]
simplex   -- Calculating MM3[FORWARD ParamMM3[af][1890,2](0.403566855061)](None).
Traceback (most recent call last):
  File "loop.py", line 183, in <module>
    main(sys.argv[1:])
  File "loop.py", line 177, in main
    loop.run_loop_input(lines)
  File "loop.py", line 106, in run_loop_input
    self.ff = loop.opt_loop()
  File "loop.py", line 40, in opt_loop
    self.loop_lines, score=self.ff.score)
  File "loop.py", line 142, in run_loop_input
    self.ff = simp.run(r_data=self.ref_data)
  File "/scratch365/ehansen3/r_rhod/opt.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/scratch365/ehansen3/r_rhod/simplex.py", line 109, in run
    data = calculate.main(self.args_ff)
  File "/scratch365/ehansen3/r_rhod/calculate.py", line 102, in main
    some_class.run(check_tokens=opts.check)
  File "/scratch365/ehansen3/r_rhod/filetypes.py", line 1105, in run
    '$SCHRODINGER/utilities/licutil -available', shell=True)
  File "/opt/crc/schrodinger/2014u1/mmshare-v25013/lib/Linux-x86_64/lib/python2.7/subprocess.py", line 537, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/opt/crc/schrodinger/2014u1/mmshare-v25013/lib/Linux-x86_64/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/opt/crc/schrodinger/2014u1/mmshare-v25013/lib/Linux-x86_64/lib/python2.7/subprocess.py", line 1143, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory


Not sure if this is related. Appears memory related. Not sure why this is happening now vs. earlier. I'm doing the same data types and training set that I've used before without issue. I'm wondering if this has something to do with my own setup here on the ND CRC.

**Comment by ericchansen** [comment]
I received this response.

"""
Dear Eric,

This error that you describe is a communication timeout issue. It might happen if a machine is overloaded with lots of i/o and file movement and I think is due to a heavy load on the hardware. It doesn't have anything to do with the number of tokens available and if it happens infrequently I would just resubmit the jobs or perhaps submit smaller jobs to try and reduce the load.

Regards,

Stuart Murdock
"""

I suppose this is something that we can only address through improved error handling.

**Comment by ericchansen** [comment]
Sometimes MacroModel just fails and there's nothing we can do. I think that commit 7fea00a and ebb75f1b256967 address this as much as we can, so I am going to close this.
